
import { RamenShop } from './types.ts';

export const MOCK_RAMEN_SHOPS: RamenShop[] = [
  {
    placeId: 'ch-1',
    name: '麺屋 龍の心 (Menya Ryunoshin)',
    photos: [
      { small: 'https://picsum.photos/seed/ramen1-main/400/300', medium: 'https://picsum.photos/seed/ramen1-main/800/600', large: 'https://picsum.photos/seed/ramen1-main/1200/900', alt: '龍の心ラーメン'},
      { small: 'https://picsum.photos/seed/ramen1-side/400/300', medium: 'https://picsum.photos/seed/ramen1-side/800/600', large: 'https://picsum.photos/seed/ramen1-side/1200/900', alt: 'サイドメニューの餃子'},
      { small: 'https://picsum.photos/seed/ramen1-shop/400/300', medium: 'https://picsum.photos/seed/ramen1-shop/800/600', large: 'https://picsum.photos/seed/ramen1-shop/1200/900', alt: '店舗の外観'},
      { small: 'https://picsum.photos/seed/ramen1-noodles/400/300', medium: 'https://picsum.photos/seed/ramen1-noodles/800/600', large: 'https://picsum.photos/seed/ramen1-noodles/1200/900', alt: 'ラーメンの麺'},
    ],
    rating: 4.5,
    address: '東京都新宿区西新宿1-1-1',
    lat: 35.690921, 
    lng: 139.700257,
    hours: '11:00 - 22:00',
    website: 'https://example.com/ryunoshin',
    twitterUrl: 'https://twitter.com/example_ramen',
    reviews: [
      { author: '佐藤健', text: '濃厚な豚骨スープが絶品！チャーシューがとろけるように柔らかく、替え玉必須です。行列が絶えないのも納得。', rating: 5, relative_time_description: '1週間前', time: 1705276800 },
      { author: '鈴木一郎', text: 'こってり好きにはたまらない一杯。麺の硬さも選べて最高でした。ニンニクをたっぷり入れるのがおすすめ。', rating: 4, relative_time_description: '2週間前', time: 1704672000 },
      { author: '高橋花子', text: 'スープは美味しかったですが、少し味が濃すぎると感じました。店内の活気は良かったです。', rating: 3, relative_time_description: '3週間前', time: 1704067200 },
      { author: '田中守', text: '週末のランチタイムはかなり混雑します。時間をずらしていくのが吉。', rating: 4, relative_time_description: '1ヶ月前', time: 1702684800 },
      { author: '伊藤由美', text: '卓上の高菜が無料で食べ放題なのが嬉しい。ラーメンとの相性も抜群。', rating: 5, relative_time_description: '1ヶ月前', time: 1702080000 },
      { author: '渡辺明', text: '店員さんの接客がとても丁寧で気持ちが良い。味だけでなく、サービスも素晴らしい。', rating: 5, relative_time_description: '2ヶ月前', time: 1699401600 },
      { author: '山本さくら', text: '麺の量は標準的。たくさん食べる人は大盛りか替え玉を検討すると良いかも。', rating: 4, relative_time_description: '2ヶ月前', time: 1698796800 },
      { author: '中村健太', text: '黒マー油が入った「黒龍ラーメン」も香ばしくておすすめ。', rating: 5, relative_time_description: '3ヶ月前', time: 1696118400 },
      { author: '小林直子', text: 'お店はカウンター席のみなので、大人数での訪問には向きません。一人か二人で行くのがベスト。', rating: 3, relative_time_description: '3ヶ月前', time: 1695513600 },
      { author: '加藤浩二', text: '何度来ても飽きない味。これぞ王道の豚骨ラーメン。', rating: 5, relative_time_description: '4ヶ月前', time: 1692835200 },
    ],
    distance: 250,
    keywords: ['豚骨', 'こってり', '行列'],
    isOpenNow: true,
    congestion: '混雑',
    accessInfo: 'JR新宿駅西口から徒歩5分',
    menu: [
      { name: '特製龍の心ラーメン', price: '1,100円' },
      { name: '味玉ラーメン', price: '950円' },
      { name: 'チャーシュー丼', price: '350円' },
      { name: '餃子 (5個)', price: '450円' },
      { name: 'ライス', price: '150円' },
      { name: '瓶ビール', price: '600円' },
    ],
    parkingInfo: '近隣にコインパーキング多数有り（提携なし）',
  },
  {
    placeId: 'ch-2',
    name: '鶏そば 白鷺 (Torisoba Shirasagi)',
    photos: [
      { small: 'https://picsum.photos/seed/ramen2-main/400/300', medium: 'https://picsum.photos/seed/ramen2-main/800/600', large: 'https://picsum.photos/seed/ramen2-main/1200/900', alt: '鶏そば'},
      { small: 'https://picsum.photos/seed/ramen2-side/400/300', medium: 'https://picsum.photos/seed/ramen2-side/800/600', large: 'https://picsum.photos/seed/ramen2-side/1200/900', alt: '鶏ハム'},
      { small: 'https://picsum.photos/seed/ramen2-shop/400/300', medium: 'https://picsum.photos/seed/ramen2-shop/800/600', large: 'https://picsum.photos/seed/ramen2-shop/1200/900', alt: '白鷺の店舗内観'},
    ],
    rating: 4.8,
    address: '東京都渋谷区道玄坂2-2-2',
    lat: 35.658034, 
    lng: 139.699998,
    hours: '11:30 - 15:00, 17:30 - 21:00',
    website: 'https://example.com/shirasagi',
    twitterUrl: 'https://twitter.com/example_ramen2',
    reviews: [
      { author: '田中美咲', text: '鶏の旨味が凝縮されたスープは、あっさりしているのに奥深い。細麺との相性も抜群。女性一人でも入りやすい雰囲気です。', rating: 5, relative_time_description: '3日前', time: 1705536000 },
      { author: '伊藤大輔', text: '非常に上品な味わいのラーメン。チャーシューの代わりに鶏ハムが乗っていてヘルシー。スープを最後まで飲み干してしまった。', rating: 5, relative_time_description: '1週間前', time: 1705104000 },
      { author: '渡辺あきら', text: '限定の柚子塩そばが最高でした。', rating: 5, relative_time_description: '2週間前', time: 1704499200 },
      { author: '中村さやか', text: '店内がとても綺麗で快適でした。', rating: 4, relative_time_description: '3週間前', time: 1703894400 },
      { author: '小林太郎', text: '麺の量が少し少なめに感じました。', rating: 3, relative_time_description: '1ヶ月前', time: 1702512000 },
      { author: '斉藤一', text: 'リピート確定です。次はつけ麺を試したい。', rating: 5, relative_time_description: '2ヶ月前', time: 1699228800 },
    ],
    distance: 480,
    keywords: ['鶏白湯', 'あっさり', '上品'],
    isOpenNow: false,
    congestion: '不明',
    accessInfo: 'JR渋谷駅ハチ公口から徒歩7分',
    menu: [
      { name: '特製鶏そば（塩）', price: '1,200円' },
      { name: '鶏そば（醤油）', price: '900円' },
      { name: '鶏白湯つけ麺', price: '1,000円' },
    ],
    parkingInfo: '駐車場なし。渋谷駅周辺の駐車場をご利用ください。',
  },
  {
    placeId: 'ch-3',
    name: '味噌の極み (Miso no Kiwami)',
    photos: [
      { small: 'https://picsum.photos/seed/ramen3-main/400/300', medium: 'https://picsum.photos/seed/ramen3-main/800/600', large: 'https://picsum.photos/seed/ramen3-main/1200/900', alt: '味噌ラーメン'},
      { small: 'https://picsum.photos/seed/ramen3-side/400/300', medium: 'https://picsum.photos/seed/ramen3-side/800/600', large: 'https://picsum.photos/seed/ramen3-side/1200/900', alt: 'バターコーンのトッピング'},
      { small: 'https://picsum.photos/seed/ramen3-shop/400/300', medium: 'https://picsum.photos/seed/ramen3-shop/800/600', large: 'https://picsum.photos/seed/ramen3-shop/1200/900', alt: '味噌の極みの店舗'},
      { small: 'https://picsum.photos/seed/ramen3-gyoza/400/300', medium: 'https://picsum.photos/seed/ramen3-gyoza/800/600', large: 'https://picsum.photos/seed/ramen3-gyoza/1200/900', alt: 'サイドの餃子'},
    ],
    rating: 4.2,
    address: '東京都豊島区東池袋3-3-3',
    lat: 35.729458, 
    lng: 139.710348,
    hours: '11:00 - 23:00',
    website: 'https://example.com/kiwami',
    reviews: [
      { author: '渡辺直樹', text: '北海道出身者も唸る本格味噌ラーメン。炒めた野菜の香ばしさがスープに溶け込んでいて最高。太ちぢれ麺がスープによく絡む。', rating: 5, relative_time_description: '5日前', time: 1705363200 },
      { author: '山本由美', text: 'バターとコーンをトッピングするのが定番。味が濃いめなので、ライスと一緒に食べるのがおすすめです。体が温まります。', rating: 4, relative_time_description: '1週間前', time: 1704931200 },
    ],
    distance: 800,
    keywords: ['味噌', '濃厚', '北海道'],
    isOpenNow: true,
    congestion: '普通',
    accessInfo: 'JR池袋駅東口から徒歩10分',
    menu: [
      { name: '極み味噌ラーメン', price: '980円' },
      { name: '辛味噌ラーメン', price: '1,050円' },
      { name: '餃子セット', price: '400円' },
    ],
    parkingInfo: '店舗裏に提携コインパーキング有り（200円割引）',
  },
  {
    placeId: 'ch-4',
    name: '煮干し中華そば 凪 (Niboshi Chuukasoba Nagi)',
    photos: [
      { small: 'https://picsum.photos/seed/ramen4-main/400/300', medium: 'https://picsum.photos/seed/ramen4-main/800/600', large: 'https://picsum.photos/seed/ramen4-main/1200/900', alt: 'すごい煮干ラーメン'},
      { small: 'https://picsum.photos/seed/ramen4-shop/400/300', medium: 'https://picsum.photos/seed/ramen4-shop/800/600', large: 'https://picsum.photos/seed/ramen4-shop/1200/900', alt: '凪の店舗'},
    ],
    rating: 4.3,
    address: '東京都千代田区丸の内4-4-4',
    lat: 35.681236, 
    lng: 139.767125,
    hours: '10:30 - 22:00',
    website: 'https://example.com/nagi',
    reviews: [
      { author: '中村拓也', text: '煮干しのパンチがすごい！好きな人はとことんハマる味。最初は驚くけど、だんだんクセになってくる。', rating: 4, relative_time_description: '2日前', time: 1705622400 },
      { author: '小林さやか', text: '煮干しの風味がガツンときます。麺は太めで食べ応えあり。好みが分かれる味かもしれませんが、私は大好きです。', rating: 5, relative_time_description: '4日前', time: 1705449600 },
    ],
    distance: 150,
    keywords: ['煮干', '醤油', '個性的'],
    isOpenNow: true,
    congestion: '空席あり',
    accessInfo: '東京メトロ大手町駅直結',
    menu: [
      { name: 'すごい煮干ラーメン', price: '900円' },
      { name: '塩煮干ラーメン', price: '900円' },
      { name: 'いったん麺', price: '150円' },
    ],
    parkingInfo: 'ビル地下駐車場利用可能（有料）',
  },
];
