name: Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [20.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 8
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
        
    - name: Install dependencies
      run: pnpm install --no-frozen-lockfile
      
    - name: Type check
      run: pnpm build
      
    - name: Run lint (if available)
      run: |
        if pnpm run | grep -q "lint"; then
          pnpm lint
        else
          echo "No lint script found, skipping"
        fi
      continue-on-error: true
      
    - name: Run tests (if available)
      run: |
        if pnpm run | grep -q "test"; then
          pnpm test
        else
          echo "No test script found, skipping"
        fi
      continue-on-error: true
      
    - name: Build project
      run: pnpm build
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-files
        path: dist/
        retention-days: 7